print("-------------Biology-------------")
printLines(42)
print("-------------Business-------------")
printLines(46)
print("-------------Classics-------------")
printLines(50)
print("-------------Comp Sci-------------")
printLines(54)
print("-------------Drama-------------")
printLines(58)
print("-------------Earth Science-------------")
printLines(62)
print("-------------Economics-------------")
printLines(67)
print("-------------Electronic Engineering-------------")
printLines(70)
print("-------------English-------------")
printLines(74)
print("-------------Geography-------------")
printLines(78)
print("-------------History-------------")
printLines(82)
print("-------------Lang, Lit, Culture Modern-------------")
printLines(86)
print("-------------Lang, Lit, Culture Comp-------------")
printLines(89)
print("-------------Lang, Lit, Culture Liberal-------------")
printLines(91)
print("-------------Law, Criminology, Sociology-------------")
printLines(94)
print("-------------Maths-------------")
printLines(98)
print("-------------Media-------------")
printLines(102)
print("-------------Music-------------")
printLines(106)
print("-------------Philosophy-------------")
printLines(110)
print("-------------Physics-------------")
printLines(114)
print("-------------Politics-------------")
printLines(118)
print("-------------Physics-------------")
printLines(122)
print("-------------Social Science-------------")
printLines(126)
print("-------------Geography-------------")
printLines(78)
print("-------------Geography-------------")
printLines(78)
print("-------------Geography-------------")
printLines(78)
print("-------------Geography-------------")
printLines(78)
print("-------------Geography-------------")
printLines(78)
